name: story_view
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.14.0
homepage: https://github.com/blackmann/story_view

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  rxdart: ^0.27.7
  video_player: ^2.5.3
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.3

flutter:
